=== zhangwei217245/weiboapitoolbox/trunk/ApiToolBox/docs/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="globalParameters"/>
				<xs:element ref="testCases"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="globalParameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="parameter"/>
				<xs:element ref="Accounts"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Accounts">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="account" maxOccurs="unbounded" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="account">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="uid"></xs:element>
                <xs:element ref="screenName"></xs:element>
                <xs:element ref="name" />
				<xs:element ref="password" />
				<xs:element ref="oauth_token" />
				<xs:element ref="oauth_secret" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:NCName" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string">
	</xs:element>
	<xs:element name="password" type="xs:string">
	</xs:element>
	<xs:element name="consumerkey">
		<xs:complexType/>
	</xs:element>
	<xs:element name="consumersecret">
		<xs:complexType/>
	</xs:element>
	<xs:element name="oauth_token" type="xs:string">
	</xs:element>
	<xs:element name="oauth_secret" type="xs:string">
	</xs:element>
	<xs:element name="testCases">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" ref="baseUrl"/>
				<xs:element maxOccurs="unbounded" ref="testCase"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="baseUrl" type="xs:string"></xs:element>
	<xs:element name="testCase">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description" maxOccurs="1"
					minOccurs="1">
				</xs:element>
				<xs:element maxOccurs="unbounded" ref="request" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string"></xs:attribute>
			<xs:attribute name="format" type="format" />
			<xs:attribute name="priority" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="request">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="reqdesc"></xs:element>
				<xs:sequence minOccurs="0">
					<xs:element ref="url" />
					<xs:element ref="method" />
					<xs:element ref="authtype" />
					<xs:element ref="accountref" />
					<xs:element ref="enctype" />
				</xs:sequence>
				<xs:element ref="parameters" />
				<xs:sequence minOccurs="0">
					<xs:element ref="valuesKeeping" />
					<xs:element ref="assertConditions" />
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="requestClass" type="xs:string"
				use="required" />
			<xs:attribute name="delayedTime" type="xs:int"></xs:attribute>
			<xs:attribute name="block_on_error" type="xs:boolean"></xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="url" type="xs:string">
	</xs:element>
	<xs:element name="method" type="httpMethod"/>
	<xs:element name="authtype" type="auth"/>
	<xs:element name="accountref" type="xs:NCName"/>
	<xs:element name="enctype" type="encType"/>
	<xs:element name="parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="parameter" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="valuesKeeping">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="expression" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="expression">
		<xs:complexType>
			<xs:attribute name="path" use="required" />
			<xs:attribute name="sessionKey" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="assertConditions">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="condition" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="condition">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="path"></xs:element>
				<xs:element name="relation" type="xs:string"></xs:element>
				<xs:element name="expectedValue" type="xs:string"></xs:element>
				<xs:element name="errorMsg" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="path">
		<xs:complexType>
			<xs:attribute name="type" type="xs:string"></xs:attribute>
			<xs:attribute name="value" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="relation">
		<xs:complexType/>
	</xs:element>
	<xs:element name="expectedValue">
		<xs:complexType/>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:attribute name="key" use="required" />
			<xs:attribute name="value" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="httpMethod">
		<xs:restriction base="xs:string">
			<xs:enumeration value="POST"/>
			<xs:enumeration value="DELETE"/>
			<xs:enumeration value="GET"/>
			<xs:enumeration value="PUT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="auth">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NULL"/>
			<xs:enumeration value="OAUTH"/>
			<xs:enumeration value="BASIC"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="format">
		<xs:restriction base="xs:string">
			<xs:enumeration value="XML"/>
			<xs:enumeration value="JSON"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="encType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="APPLICATION"/>
			<xs:enumeration value="MULTIPART"/>
		</xs:restriction>
	</xs:simpleType>

    <xs:element name="description" type="xs:string"></xs:element>

    <xs:element name="reqdesc" type="xs:string"></xs:element>

    <xs:element name="uid" type="xs:string"></xs:element>

    <xs:element name="screenName" type="xs:string"></xs:element>
</xs:schema>

=== zhangwei217245/weiboapitoolbox/trunk/ApiToolBox/docs/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">
    <globalParameters>
        <parameter key="consumerKey" value="1852823608"/>
        <parameter key="consumerSecret" value="f7623417c5fbe029dd366e4e01e34e48"/>
        <Accounts>
            <account id="A">
                <uid>1803876591</uid>
                <screenName>LoopA</screenName>
                <name>loopa@sina.cn</name>
                <password>123456</password>
                <oauth_token>07ab6a78fcc18a624a472a1bc7c274e7</oauth_token>
                <oauth_secret>a66c4cc49a652d2c981bbda82bd9a746</oauth_secret>
            </account>
            <account id="B">
                <uid>1803880061</uid>
                <screenName>LoopB</screenName>
                <name>loopb@sina.cn</name>
                <password>123456</password>
                <oauth_token>76eee405d795677482af833a118c7664</oauth_token>
                <oauth_secret>309d81204c4f94ed1710461cdd329229</oauth_secret>
            </account>
            <account id="C">
                <uid>1803888563</uid>
                <screenName>LoopC</screenName>
                <name>loopc@sina.cn</name>
                <password>123456</password>
                <oauth_token>4698b31925b713c25052f508d22ceeb2</oauth_token>
                <oauth_secret>e9692337cef02a775e05aed4f3a3471f</oauth_secret>
            </account>
            <account id="D">
                <uid>1803882341</uid>
                <screenName>LoopD</screenName>
                <name>loopd@sina.cn</name>
                <password>123456</password>
                <oauth_token>aa1ae9d4f2a23a3c44c137ca8586cfa3</oauth_token>
                <oauth_secret>4e6cded8fef0fb492715e429bec39292</oauth_secret>
            </account>
      
        </Accounts>
    </globalParameters>
    <testCases>
  	
        <baseUrl>http://api.t.sina.com.cn</baseUrl>
	
        <testCase format="XML" id="1" priority="H">
            <description>测试微博的发表、删除</description>
            <request requestClass="com.sina.weibo.looptest.request.CommonLoopRequest" block_on_error="true">
                <reqdesc>发表一篇微博</reqdesc>
                <url>statuses/update</url>
                <method>POST</method>
                <authtype>BASIC</authtype>
                <accountref>A</accountref>
                <enctype>APPLICATION</enctype>
                <parameters>
                    <parameter key="status" value="${random:string(5)}"/>
                </parameters>
                <valuesKeeping>
                    <expression sessionKey="status_0" path="status/text/text()"></expression>
                    <expression sessionKey="status_id_0" path="status/id/text()"></expression>
                </valuesKeeping>
                <assertConditions>
                    <condition>
                        <path type="S" value="status/text/text()"/>
                        <relation>eq</relation>
                        <expectedValue>${reqParam:status}</expectedValue>
                        <errorMsg>返回的微博文本与发表的微博文本不一致</errorMsg>
                    </condition>
                </assertConditions>
            </request>
      
            <request requestClass="com.sina.weibo.looptest.request.CommonLoopRequest" delayedTime="180000">
                <reqdesc>根据ID验证微博</reqdesc>
                <url>statuses/show/${session:status_id_0}</url>
                <method>GET</method>
                <authtype>BASIC</authtype>
                <accountref>A</accountref>
                <enctype>APPLICATION</enctype>
                <parameters/>
                <valuesKeeping/>
                <assertConditions>
                    <condition>
                        <path type="S" value="status/text/text()"/>
                        <relation>eq</relation>
                        <expectedValue>${session:status_0}</expectedValue>
                        <errorMsg>根据ID查到的微博文本和发表的微博文本不一致</errorMsg>
                    </condition>
                    <condition>
                        <path type="S" value="status/id/text()"/>
                        <relation>eq</relation>
                        <expectedValue>${session:status_id_0}</expectedValue>
                        <errorMsg>根据ID查到的微博ID和发表的微博ID不一致</errorMsg>
                    </condition>
                </assertConditions>
            </request>

            <request requestClass="com.sina.weibo.looptest.request.CommonLoopRequest">
                <reqdesc>判断当前用户发表的微博列表中是否已存在刚发布的微博</reqdesc>
                <url>statuses/user_timeline</url>
                <method>GET</method>
                <authtype>BASIC</authtype>
                <accountref>A</accountref>
                <enctype>APPLICATION</enctype>
                <parameters/>
                <valuesKeeping/>
                <assertConditions>
                    <condition>
                        <path type="M" value="statuses/status/text/text()"/>
                        <relation>contains</relation>
                        <expectedValue>${session:status_0}</expectedValue>
                        <errorMsg>当前用户的微博列表中找不到刚发布的微博文本</errorMsg>
                    </condition>
                    <condition>
                        <path type="M" value="statuses/status/id/text()"/>
                        <relation>contains</relation>
                        <expectedValue>${session:status_id_0}</expectedValue>
                        <errorMsg>当前用户的微博列表中找不到刚发布的微博ID</errorMsg>
                    </condition>
                </assertConditions>
            </request>

            <request requestClass="com.sina.weibo.looptest.request.CommonLoopRequest" block_on_error="true">
                <reqdesc>根据ID删除微博</reqdesc>
                <url>statuses/destroy/${session:status_id_0}</url>
                <method>DELETE</method>
                <authtype>BASIC</authtype>
                <accountref>A</accountref>
                <enctype>APPLICATION</enctype>
                <parameters/>
                <valuesKeeping/>
                <assertConditions>
                    <condition>
                        <path type="S" value="status/text/text()"/>
                        <relation>eq</relation>
                        <expectedValue>${session:status_0}</expectedValue>
                        <errorMsg>返回的微博文本与被删除的微博文本不一致</errorMsg>
                    </condition>
                    <condition>
                        <path type="S" value="status/id/text()"/>
                        <relation>eq</relation>
                        <expectedValue>${session:status_id_0}</expectedValue>
                        <errorMsg>返回的微博ID与被删除的微博ID不一致</errorMsg>
                    </condition>
                </assertConditions>
            </request>

            <request requestClass="com.sina.weibo.looptest.request.CommonLoopRequest"  delayedTime="180000">
                <reqdesc>根据ID查找微博</reqdesc>
                <url>statuses/show/${session:status_id_0}</url>
                <method>GET</method>
                <authtype>BASIC</authtype>
                <accountref>A</accountref>
                <enctype>APPLICATION</enctype>
                <parameters/>
                <valuesKeeping/>
                <assertConditions>
                    <condition>
                        <path type="S" value="hash/error_code/text()"></path>
                        <relation>eq</relation>
                        <expectedValue>400</expectedValue>
                        <errorMsg>删除微博后根据ID查找被删除微博状态码不为400</errorMsg>
                    </condition>
                    <condition>
                        <path type="S" value="hash/error/text()"></path>
                        <relation>contains</relation>
                        <expectedValue>target weibo does not exist</expectedValue>
                        <errorMsg>根据ID查找被删除微博没有提示目标微博不存在的信息</errorMsg>
                    </condition>
                </assertConditions>
            </request>

            <request requestClass="com.sina.weibo.looptest.request.CommonLoopRequest">
                <reqdesc>判断当前用户发表的微博列表中是否还存在刚发布的微博</reqdesc>
                <url>statuses/user_timeline</url>
                <method>GET</method>
                <authtype>BASIC</authtype>
                <accountref>A</accountref>
                <enctype>APPLICATION</enctype>
                <parameters/>
                <valuesKeeping/>
                <assertConditions>
                    <condition>
                        <path type="M" value="statuses/status/text/text()"/>
                        <relation>ncontains</relation>
                        <expectedValue>${session:status_0}</expectedValue>
                        <errorMsg>被删除的微博文本仍然出现在当前用户的微博列表内</errorMsg>
                    </condition>
                    <condition>
                        <path type="M" value="statuses/status/id/text()"/>
                        <relation>ncontains</relation>
                        <expectedValue>${session:status_id_0}</expectedValue>
                        <errorMsg>被删除的微博ID仍然出现在当前用户的微博列表内</errorMsg>
                    </condition>
                </assertConditions>
            </request>
      
        </testCase>
	
        <testCase format="JSON" id="2" priority="H">
            <description>测试微博的发表、删除</description>
            <request requestClass="com.sina.weibo.looptest.request.CommonLoopRequest"  block_on_error="true">
                <reqdesc>发表一篇微博</reqdesc>
                <url>statuses/update</url>
                <method>POST</method>
                <authtype>BASIC</authtype>
                <accountref>A</accountref>
                <enctype>APPLICATION</enctype>
                <parameters>
